### ISSUE TITLE
Error not clear when argument should be a pointer, but is not

### ISSUE THREAD

**Issue by ghostsquad** [golang/mock#319] opened 2019-07-29 17:51 UTC
When a function expects a pointer to a struct, but your gomock expect isn't using a pointer, it is hard to tell that is the problem.

This Fails with the output (down below)
```go
m.EXPECT().UpdateAutoScalingGroupWithContext(ctx, autoscaling.UpdateAutoScalingGroupInput{
			AutoScalingGroupName: aws.String(expectedASGName),
			MinSize: aws.Int64(expectedMinSize),
			MaxSize: aws.Int64(expectedMaxSize),
			DesiredCapacity: aws.Int64(expectedDesiredCapacity),
			LaunchTemplate: expectedLts,
		}).Return(nil, nil)
```

This succeeds. (using a pointer to the `UpdateAutoScalingGroupInput`)
```go
m.EXPECT().UpdateAutoScalingGroupWithContext(ctx, &autoscaling.UpdateAutoScalingGroupInput{
			AutoScalingGroupName: aws.String(expectedASGName),
			MinSize: aws.Int64(expectedMinSize),
			MaxSize: aws.Int64(expectedMaxSize),
			DesiredCapacity: aws.Int64(expectedDesiredCapacity),
			LaunchTemplate: expectedLts,
		}).Return(nil, nil)
```

```
=== FAIL: pkg/aws TestASGPreparerImpl_Prepare/expect_params_passed_to_update_call (0.00s)
    --- FAIL: TestASGPreparerImpl_Prepare/expect_params_passed_to_update_call (0.00s)
        asgpreparer.go:28: Unexpected call to *aws.MockAutoScalingAPI.UpdateAutoScalingGroupWithContext([context.TODO.WithValue("test", "test") {
              AutoScalingGroupName: "foo",
              DesiredCapacity: 4,
              LaunchTemplate: {

              },
              MaxSize: 5,
              MinSize: 4
            }]) at <REDACTED>/asgclient_mock_test.go:2989 because:
            Expected call at <REDACTED>_test.go:60 doesn't match the argument at index 1.
            Got: {
              AutoScalingGroupName: "foo",
              DesiredCapacity: 4,
              LaunchTemplate: {

              },
              MaxSize: 5,
              MinSize: 4
            }
            Want: is equal to {
              AutoScalingGroupName: "foo",
              DesiredCapacity: 4,
              LaunchTemplate: {

              },
              MaxSize: 5,
              MinSize: 4
            }
        panic.go:406: missing call(s) to *aws.MockAutoScalingAPI.UpdateAutoScalingGroupWithContext(is equal to context.TODO.WithValue("test", "test"), is equal to {
              AutoScalingGroupName: "foo",
              DesiredCapacity: 4,
              LaunchTemplate: {

              },
              MaxSize: 5,
              MinSize: 4
            }) <REDACTED>_test.go:60
        panic.go:406: aborting test due to missing call(s)

```

**Comment by poy** [comment] 2019-08-11 06:41
Do you have an idea on what you would hope the output would look like?

**Comment by ghostsquad** [comment] 2019-08-11 18:21
https://play.golang.org/p/ydo2kwkzO04

```
wanted: {}, but got &{}
```

The first character says it all. But you could go one step further, and evaluate explicitly if `A` was a pointer and `B` was not, or vice versa, are print something like:

```
expected a pointer, but received a value
```

```
expected a value, but received a pointer
```

**Comment by tscott0** [comment] 2019-08-20 20:11
This would be great! Everyone makes mistakes like this and the current output doesn't give us any clues. There is no difference between the Got and Want.

I prefer the second suggestion as it's a bit more readable. It's easy to miss the ampersand in the test output.

@ghostsquad, to clarify, do you mean that you would expect to see "expected a pointer, but received a value" _only_ if `A` was a pointer to the same type as `B`? For example, if `A` was a `*string` and `B` was a `string`.

**Comment by ghostsquad** [comment] 2019-08-21 05:35
@tscott0 I think the current behavior just skips a vital step, in that it immediately performs (and prints) a deep comparison. The most important thing before doing a deep comparison is what the top-level values are. Maybe something  like this?

```
Unexpected call to *aws.MockAutoScalingAPI.UpdateAutoScalingGroupWithContext

Argument Type Mismatch for argument 2 (index 1)

Expected Type: &UpdateAutoscalingGroupInput
Received Type: UpdateAutoscalingGroupInput
```

Also there needs to be consideration for when the _test_ is setup incorrectly. If I'm mocking a method that takes a struct pointer, and I do something like this:

```
m.EXPECT().Foo(Bar{})
```

I think the error should be:

```
Invalid mock expectation. `Foo` requires argument 1 type: `&Bar{}`, but expectation used was `Bar{}`

As of this writing, I don't recall what happens when expectations are incorrectly written.

**Comment by codyoss** [comment] 2019-10-18 19:47
@ghostsquad would you consider this a dupe of #190?

**Comment by ghostsquad** [comment] 2019-10-18 22:33
@codyoss I think so

**Comment by codyoss** [comment] 2019-10-18 22:55
@ghostsquad awesome, I will close this one so we can have a more focused conversation on the older issue. I would like to see this feature get some attention as well!

**Closed by codyoss** 2019-10-18 22:55 UTC
Labels: type: feature request
