### ISSUE TITLE
Controller needs to be initialized inside subtests

### ISSUE THREAD

**Issue by motomux** [golang/mock#51] opened 2016-08-19 08:20 UTC
When we use mock with subtests, we need to initialize controller inside subtests.
If we initialize it outside of subtests and mock is not called expected, it outputs useless error which is `panic: test executed panic(nil) or runtime.Goexit`

good test

```
func TestSomething(t *testing.T) {
    t.Run("good", func(t *testing.T) {
        mockCtrl := gomock.NewController(t)
        defer mockCtrl.Finish()

        // test something
    })
}
```

bad test

```
func TestSomething(t *testing.T) {
    mockCtrl := gomock.NewController(t)
    defer mockCtrl.Finish()

    t.Run("bad", func(t *testing.T) {
        // test something
    })
}
```

I think this should be documented.

**Comment by Soulou** [comment] 2017-08-23 17:37
This issues seems not fixed at all I can still reproduce it, it's related to go itself:

* https://github.com/golang/go/issues/17421

A patch a few weeks ago addressed this by adding comments, which is not very satisfying:

* https://github.com/golang/go/commit/bd74fd3abb27b9b857ca77c9ee648299045ce963
* https://go-review.googlesource.com/c/go/+/52770/3/src/testing/testing.go

Do you have an idea how to handle this?

Thanks a lot.

**Comment by balshetzer** [comment] 2017-08-23 17:56
This was closed by mistake. The change that closed it fixed 52 not 51.

**Comment by balshetzer** [comment] 2017-08-23 18:32
Here is a summary of the problem. 

The user means to do this:
func TestSomething(t1 *testing.T) {
  t1.Run("nested", func(t2 *testing.T) {
    t2.Fatal("useful error message") // note use of t2, not t1
  }
}
and the output would be helpful:
--- FAIL: TestSomething (0.00s)
    --- FAIL: TestSomething/nested (0.00s)
        test_test.go:7: useful error message
FAIL

But, the user does this:
func TestSomething(t1 *testing.T) {
  t1.Run("nested", func(t2 *testing.T) {
    t1.Fatal("useful error message") // error! should be t2.Fatal
  }
}
Then the output is less helpful:
panic: test executed panic(nil) or runtime.Goexit

This is what happens when the mock's controller is created outside t.Run. The controller takes t as an argument and uses t.Fatalf when something goes wrong. But that's the wrong t to use so we get this confusing error.

It would be nice if this could be fixed in the testing package. I agree that the comment solution is unsatisfying. It would be much better if the testing package could detect that the wrong t.Fatal was called and say so.

This seems difficult to fix in gomock.

The way for the programmer to handle this is to create the controller inside t.Run and use the correct t when creating the controller.

**Comment by Soulou** [comment] 2017-08-23 18:46
Ok thanks for these details, it's much more clear to me.

So the main problem it creates is that we're now obliged to repeat a lot of code if I got that well:

```
func TestFoo1(t *testing.T) {
	t.Run("sub test 1", func(t *testing.T) {
		ctrl := gomock.NewController(t)
		defer ctrl.Finish()
		m := NewMockType(ctrl)
		m.EXPECT().Method1().Return(nil)
                // ...
	})
	t.Run("sub test 2", func(t *testing.T) {
		ctrl := gomock.NewController(t)
		defer ctrl.Finish()
		m := NewMockType(ctrl)
		m.EXPECT().Method1().Return(errors.New("error"))
                // ...
	})
}
```

Instead of the logical:

```
func TestFoo1(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	m := NewMockType(ctrl)

	t.Run("sub test 1", func(t *testing.T) {
		m.EXPECT().Method1().Return(nil)
                // ...
	})
	t.Run("sub test 2", func(t *testing.T) {
		m.EXPECT().Method1().Return(errors.New("error"))
                // ...
	})
}
```

**Comment by frairon** [comment] 2018-05-15 15:11
Same issue here.
If that helps anyone, here's a little workaround that we're using to wrap the testing.T and replace it with the one from the subtest:

```go

type subreporter struct {
	t []gomock.TestReporter
}

func newSubreporter(t gomock.TestReporter) *subreporter {
	return &subreporter{
		t: []gomock.TestReporter{t},
	}
}

func (r *subreporter) add(t gomock.TestReporter) func() {
	r.t = append(r.t, t)
	return func() {
		r.t = r.t[:len(r.t)-1]
	}
}

func (r *subreporter) Errorf(format string, args ...interface{}) {
	r.t[len(r.t)-1].Errorf(format, args...)
}
func (r *subreporter) Fatalf(format string, args ...interface{}) {
	r.t[len(r.t)-1].Fatalf(format, args...)
}
```

The subreporter implements the same interface required by gomock. In every subtest, the current `t` is then added to the subreporter and removed at the end of the test. 
The stacking instead of replacing `t` is helpful if you have nested subtests or need to use the controller after the subtests.

Example usage (in the example above):

```go
func TestFoo1(t *testing.T) {
	r      = newSubreporter(t)
	ctrl := gomock.NewController(r)
	defer ctrl.Finish()
	m := NewMockType(ctrl)

	t.Run("sub test 1", func(t *testing.T) {
                defer r.add(t)()
		m.EXPECT().Method1().Return(nil)
                // ...
	})
	t.Run("sub test 2", func(t *testing.T) {
                defer r.add(t)()
		m.EXPECT().Method1().Return(errors.New("error"))
                // ...
	})
}
```

I know it's still boilerplate code to add, but less than adding the code to create the controller and the mocks every time in the subtest, which kind of makes them useless.

**Comment by codyoss** [comment] 2019-10-12 20:22
I think the best we can do for now here is to provide some better docs? Thoughts?

**Comment by frairon** [comment] 2019-10-18 16:46
Actually it's already documented here since Dec 2018: https://godoc.org/github.com/golang/mock/gomock#Controller
What could be added to the docs is a snippet with the workaround if you prefer to instantiate the controller outside the subtests.
On the other hand though, if we assume there's only one controller in a test, we could even add a method similar to `t.Run` with the same interface that does the T-rewire internally and should be used when gomock is used in conjunction with subtests. Not sure if that is too dirty. If not I'm happy to give it a try.

**Comment by codyoss** [comment] 2019-10-18 17:47
For now I think just a docs update would be great. If you want to make that @frairon I am open to PRs! Or else it might be a bit until I can get to this.

**Comment by codyoss** [comment] 2020-02-22 21:45
I am going to close this out as there is not much actionable to do. @frairon If you would like to open a feature request and take a stab at something the project is always open to PRs 😸

**Closed by codyoss** 2020-02-22 21:45 UTC
Labels: help wanted, type: docs
