### ISSUE TITLE
Mockgen: Support generating mock for interfaces with generics

### ISSUE THREAD

**Issue by lingyv-li** [golang/mock#621] opened 2022-02-13 00:12 UTC
*Requested feature*

Mockgen should support generating mocks for interfaces with generics.

*Why the feature is needed*
The Go 1.18 is planned to be released soon, and I noticed that the mockgen tool doesn't support the generic.  When a type parameter is in the interface, mockgen will throw an error.

Code example: https://go.dev/play/p/g1G2OvZPQpT?v=gotip

```shell
> go run github.com/golang/mock/mockgen -source=generic_mock.go
2022/02/13 10:59:41 Loading input failed: don't know how to mock method of type *ast.IndexExpr
exit status 1
```

*(Optional) Proposed solution*

1. In the code example above, the `StudentRepository` interface is concrete, so the gererated mock should be concrete too with the type parameters substituted.
2. The `BaseRepository` interface is abstract, so the generated mock struct should also have the same type parameters.

(My use case only needs 1, which mockery supports as of today.)

**Comment by CannibalVox** [comment] 2022-02-28 01:03
In fact, I've gotten errors generating mocks for interfaces that don't use generics but are located in packages that do use generics. So I think this might be a slightly more serious issue than it appears at first glance.

**Comment by codyoss** [comment] 2022-02-28 15:29
Hey, this is planned and will try to land as a fast followup to 1.18. Thank you for the request!

**Comment by abramk** [comment] 2022-03-22 19:09
Do you have a rough idea of when we can expect a generics compatible release? This is the main impediment for us to aggressively adopt generic goodness.

**Comment by CannibalVox** [comment] 2022-03-23 01:06
FWIW I was able to work around the above issue by moving interfaces out to their own file that don't use generics. That doesn't help for cases where you want the interface itself to use generics, but it did help for my case.

**Comment by abramk** [comment] 2022-03-31 10:06
I don't believe the above is possible with go generics. The code has no way of reflecting on the type of the actual parameter.

**Comment by powerman** [comment] 2022-04-10 19:15
Looks like it's possible to work around this issue by using type aliases:
```go
// Broken:
type Target interface {
    Method() *generic.Type[int]
}

// Working:
type GenericTypeInt = generic.Type[int]
type Target interface {
    Method() *GenericTypeInt
}
```

**Comment by swallowtail62** [comment] 2022-04-11 09:09
@powerman 
It works for me. thank you.

**Comment by sodul** [comment] 2022-04-18 17:46
@codyoss Now that Go 1.18 has been out for over a month, is there a timeline update you can share? Thank you!

**Comment by bradleygore** [comment] 2022-04-19 23:47
The solution proposed by @powerman doesn't work for generics working with custom types from what I can see:
```
// generic thing in foo pkg
type Gen [T any] struct {
  Items []T
  // other fields
}

// package bar

type Thing struct {
  FirstName string
}

type GenericTypeGenThing = Gen[*Thing]

// interface I want to generate a mock for
type Thinger interface {
  Get() GenericTypeGenThing
}
```

What I see happening is that the generated output is like this for the generic return parameter: `foo.Gen[*path/to/bar.Thing]`

**Comment by powerman** [comment] 2022-04-20 00:39
> What I see happening is that the generated output is like this for the generic return parameter: `foo.Gen[*path/to/bar.Thing]`

At a glance there is a typo in your example code, this line probably should be:

```go
type GenericTypeGenThing = foo.Gen[*Thing] // Added "foo." here.
```

Unlikely this is the actual problem, because without "foo." it shouldn't compile at all. Anyway, working example in some temp repo would be useful to understand why workaround doesn't works for you.

**Comment by bradleygore** [comment] 2022-04-20 00:42
Yeah, that's a typo but not the issue. As you said, it wouldn't have compiled if that were the issue. That's what I get for hastily making a contrived example based on the real one 😝 

I appreciate your looking into it!

**Comment by bradleygore** [comment] 2022-04-20 02:08
@powerman I have set up a repository with reproduction of a couple different issues with generics and `mockgen`: [gomock-generics-issue](https://github.com/bradleygore/gomock-generics-issue)

**Comment by herlon214** [comment] 2022-04-20 17:14
I'm looking forward for this.

**Comment by codyoss** [comment] 2022-04-24 19:28
Thanks for all the good discussion here folks. I have some time set aside this week to try to implement something here. I will likely put this out in a beta release as I want to make sure this change lands well. Thanks for the patience.

**Comment by herlon214** [comment] 2022-05-05 19:08
@codyoss thank you very much! i will do some tests tomorrow morning 🚀

**Comment by herlon214** [comment] 2022-05-06 13:12
@codyoss I tried here and it panic:
```
mockgen -package=mock -source=service.go -destination=mock/svc.go
panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

goroutine 1 [running]:
main.(*fileParser).parseGenericType(0x6f3aa0?, {0xc00021a200?, 0xc0002030b0?}, {0x7ca958?, 0xc000202510?}, 0xc00012d3b0?)
        /home/herlon/dev/codyoss/mock/mockgen/generic_go118.go:38 +0x23f
main.(*fileParser).parseType(0xc00012dd10?, {0xc00021a200?, 0x3a?}, {0x7ca958?, 0xc000202510?}, 0x8?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:545 +0xbd6
main.(*fileParser).parseType(0xc00012dd10, {0xc00021a200, 0x3a}, {0x7cabc8?, 0xc000208180?}, 0x8?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:532 +0x5c9
main.(*fileParser).parseFieldList(0xc000218330?, {0xc00021a200, 0x3a}, {0xc00020a0c0, 0x2, 0x50?}, 0xc00020a2c0?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:435 +0x13c
main.(*fileParser).parseFunc(0x6f6080?, {0xc00021a200?, 0x3a?}, 0xc0002126e0, 0x51ccbf?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:412 +0x345
main.(*fileParser).parseInterface(0xc00012dd10, {0xc000218054, 0x7}, {0xc00021a200, 0x3a}, 0xc000202e70)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:300 +0x769
main.(*fileParser).parseFile(0xc00012dd10, {0xc00021a200, 0x3a}, 0xc00020e100)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:232 +0x2d1
main.sourceMode({0x7fff0baf7c9e, 0x22})
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:90 +0x40d
main.main()
        /home/herlon/dev/codyoss/mock/mockgen/mockgen.go:81 +0x2ea
 ```
 
 I'm trying to generate a mock for an interface which uses generic structs
 ```go
type Service interface {
	Create(ctx context.Context, params Params, input Input) error
	Update(ctx context.Context, params Params, input Input) error
	List(ctx context.Context, params Params, filters Filters) (*controller.Results[Output], error)
	Fetch(ctx context.Context, params Params) (*controller.Result[Output], error)
	Delete(ctx context.Context, params Params) error
}
```

In the case above my generic struct is `controller.Result[Output]` and `controller.Results[Output]`.

**Comment by codyoss** [comment] 2022-05-06 15:29
@herlon214 Thank you for taking the time to try out the branch. I think you may have missed a step in your testing perhaps? I added two more test cases that should cover your use case and it worked for me. To test make sure you:

1. Checkout the branch
2. Rebuild mockgen with that source with Go 1.18: `go install ./...` . Code updates are required for the generator to parse these new ast types in 1.18
3. Generate your mocks and test with by replacing the local branch with a version of mock recorded in your go.mod: `go mod edit -replace github.com/golang/mock=/Path/To/Checked/Out/Code`

Can you confirm that you rebuilt mockgen, I suspect that that is why you might be getting that error.

**Comment by herlon214** [comment] 2022-05-06 16:18
@codyoss here are the steps I did:

* Removed my mockgen binary from my go path
* Cloned your repo
* Checked out the `generics` branch
* Ran `go install ./...`
* Checked if the mockgen binary is there
* Cd into my project
* Ran `mockgen -package=mock -source=service.go -destination=mock/service.go` to generate the mock

```
goroutine 1 [running]:
main.(*fileParser).parseGenericType(0x6f3aa0?, {0xc000018500?, 0xc0000a0ff0?}, {0x7ca958?, 0xc0000a0450?}, 0xc00020f3b0?)
        /home/herlon/dev/codyoss/mock/mockgen/generic_go118.go:38 +0x23f
main.(*fileParser).parseType(0xc00020fd10?, {0xc000018500?, 0x3a?}, {0x7ca958?, 0xc0000a0450?}, 0x8?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:545 +0xbd6
main.(*fileParser).parseType(0xc00020fd10, {0xc000018500, 0x3a}, {0x7cabc8?, 0xc00000c1b0?}, 0x8?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:532 +0x5c9
main.(*fileParser).parseFieldList(0xc00001c470?, {0xc000018500, 0x3a}, {0xc0000800d0, 0x2, 0x50?}, 0xc0000802d0?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:435 +0x13c
main.(*fileParser).parseFunc(0x6f6080?, {0xc000018500?, 0x3a?}, 0xc00008a700, 0x51ccbf?)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:412 +0x345
main.(*fileParser).parseInterface(0xc00020fd10, {0xc00001c194, 0x7}, {0xc000018500, 0x3a}, 0xc0000a0db0)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:300 +0x769
main.(*fileParser).parseFile(0xc00020fd10, {0xc000018500, 0x3a}, 0xc0000a2080)
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:232 +0x2d1
main.sourceMode({0x7ffea3a7ec05, 0x22})
        /home/herlon/dev/codyoss/mock/mockgen/parse.go:90 +0x40d
main.main()
        /home/herlon/dev/codyoss/mock/mockgen/mockgen.go:81 +0x2ea
```
Couldn't finish the step `(3)` you mentioned, once the mocks aren't generated.

Did I miss anything?

**Comment by codyoss** [comment] 2022-05-06 16:30
@herlon214 What you did looks good, I think I see what the issue is now. I will try to get a patch out later today for this use case. Thank you for the report!

**Comment by codyoss** [comment] 2022-05-06 17:12
@herlon214 I think the issue you were seeing now should be fixed. Had not accounted for generic structs that don't use type params from the interface.

**Comment by herlon214** [comment] 2022-05-08 11:53
@codyoss looks like it worked now!
I'm gonna do more tests tomorrow and let you know, thanks in advance!!

**Comment by herlon214** [comment] 2022-05-09 10:06
Hey @codyoss I found another issue (kinda). I have a type which aliases one generic type:
```
type Persistence mongodb.Persistence[User]
```

The generated mocks for that are:
```
// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/v1/domain/appdefinition/persistence.go

// Package mock is a generated GoMock package.
package mock

```

**Comment by codyoss** [comment] 2022-05-11 02:50
@herlon214 Can you clarify what the issue is?

**Comment by herlon214** [comment] 2022-05-11 09:41
@codyoss the generated mocks are actually empty, that's the issue.
`mongodb.Persistence` is:
```go
type Persistence[T any] interface {
	List(ctx context.Context, filter bson.M) ([]T, error)
	Fetch(ctx context.Context, filter bson.M) (*T, error)
	Create(ctx context.Context, input T) error
	Update(ctx context.Context, filter bson.M, item T) error
	Delete(ctx context.Context, filter bson.M) error
}
```

So I would expect that using `type Persistence mongodb.Persistence[User]` would generate the mocks for it, but the result is one file with the package name and some comments:
```
// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/v1/domain/user/persistence.go

// Package mock is a generated GoMock package.
package mock
```

Nothing else ^

**Comment by codyoss** [comment] 2022-05-12 03:01
@herlon214 That is as intended, the type needs to be an interface. This is the same for non-generic types too.

**Comment by codyoss** [comment] 2022-05-12 03:07
Support for source mode is now merged. I hope to get reflect done with week too and then I will publish a beta release to get feedback to make sure things are working as intended

**Comment by herlon214** [comment] 2022-05-12 09:25
@codyoss considering that `mongodb.Persistence` is an generic interface, shouldn't `type Persistence mongodb.Persistence[User]` become an interface as well? but applying one specific type to that generic interface.

**Comment by codyoss** [comment] 2022-05-12 14:30
@herlon214 Maybe. But like I said, this does not work for non-generic types today either. If anything that should be a separate issue if people have use cases for this. The way mockgen treats aliases is already not great. Depending if you use reflect vs source mode the alias will be followed or not.

**Comment by herlon214** [comment] 2022-05-12 16:45
@bradleygore Also doesn't work.
But generating the mocks directly to `mongodb.Persistence[T any]` looks like it works fine.

Thanks again @codyoss, great job!

**Comment by bradleygore** [comment] 2022-05-12 16:55
hmm, yeah this may be interesting for my use-case. Consider a repository setup:

```
type BaseRepo interface[T any] {
  Get(filters *Filters) (*PagedResults[T], error)
  GetByID(int64) (T, error)
  Create(T) error
  Update(T) error
  Delete(T) error
}

type UserRepo interface {
  BaseRepo[User]
  FindByEmail(string email) (*User, error)
}
```

@codyoss - any thoughts on this and if it should be supported, or should this actually be structured differently?

**Comment by bradleygore** [comment] 2022-05-12 17:02
Sounds good - will try to test soon. Thanks for all your efforts on this @codyoss 😃

**Comment by bradleygore** [comment] 2022-05-12 17:49
I went ahead and created a new issue for this - there is still an issue with type annotations across packages. I have a fairly thorough issue repo set up at https://github.com/bradleygore/gomock-generics-issue and the issue I just wrote up is at https://github.com/golang/mock/issues/643 .

Again - thanks for all efforts on this front!

**Comment by DanielSolomon** [comment] 2022-05-19 07:08
I also faced another issue with Generics, in case I use a concrete type:

```
type Pagination struct {
	Limit int64
	Skip  int64
}

//go:generate mockgen -source=$GOFILE -destination=mocks/autogen.$GOFILE -package=mocks
type IMongoDbClient interface {
	GetMany(ctx context.Context, collectionName string, filter bson.M, pagination optional.Optional[Pagination]) error
}

```
`Optional` is defined in other package as:
```
type Optional[T any] struct {
	value   T
	present bool
}
```

When running `go generate ./...`, the following error is raised:
```
2022/05/19 10:01:58 Loading input failed: failed parsing source file api.go: api.go:43:97: missing ',' in parameter list
lib/go/mongo/client/api.go:41: running "mockgen": exit status 1
```

Also tried using `main` branch (v1.6.1-0.20220512030613-73266f9366fc), still same error.
Also tried using the workaround above:
```
type OptionalPagination = optional.Optional[Pagination]
```
Result in:
```
Loading input failed: failed parsing source file api.go: api.go:41:44: expected ';', found '['
lib/go/mongo/client/api.go:43: running "mockgen": exit status 1
```

**Comment by 0x4c6565** [comment] 2022-05-20 07:46
> The solution proposed by @powerman doesn't work for generics working with custom types from what I can see:
> 
> ```
> // generic thing in foo pkg
> type Gen [T any] struct {
>   Items []T
>   // other fields
> }
> 
> // package bar
> 
> import "path/to/foo"
> 
> type Thing struct {
>   FirstName string
> }
> 
> type GenericTypeGenThing = foo.Gen[*Thing]
> 
> // interface I want to generate a mock for
> type Thinger interface {
>   Get() GenericTypeGenThing
> }
> ```
> 
> What I see happening is that the generated output is like this for the generic return parameter: `foo.Gen[*path/to/bar.Thing]`

It would appear that using gomock `Reflect` mode results in this too:

## Source

```
package testpackage

import "github.com/someorg/testproject/pkg/connection"

type TestStruct struct {}

type SomeTestService interface {
	SomeTestMethod(parameters connection.APIRequestParameters) (*connection.Paginated[TestStruct], error)
}
```

## Command
```
mockgen -package mocks -destination mock_sometestservice.go github.com/someorg/testproject/pkg/testpackage SomeTestService
```

## Output

```
// SomeTestMethod mocks base method.
func (m *MockSomeTestService) SomeTestMethod(arg0 connection.APIRequestParameters) (*connection.Paginated[github.com/someorg/testproject/pkg/testpackage.TestStruct], error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "SomeTestMethod", arg0)
        ret0, _ := ret[0].(*connection.Paginated[github.com/someorg/testproject/pkg/testpackage.TestStruct])
        ret1, _ := ret[1].(error)
        return ret0, ret1
}
```

**Comment by codyoss** [comment] 2022-05-27 17:43
Looked more into reflect mode and I don't think implementing generics support for reflect mode will work. Reflect works with runtime types and by just looking at an interface with constraints there is no way to get these runtime types. At least for the initial release of support generics will only be supported in source mode. If I overlooked something here please feel free to correct me. For now I am closing out this issue as initial support has landed on HEAD. I plan on releasing a beta tag of this next week.

**Closed by codyoss** 2022-05-27 17:43 UTC
Labels: type: feature request

**Comment by DanielSolomon** [comment] 2022-05-27 18:04
Hey @codyoss , I see you closed the issue, but when I update `mockgen` I still get the same error I attached [above](https://github.com/golang/mock/issues/621#issuecomment-1131310245), should I create an issue on it? or am I using something incorrectly?

**Comment by codyoss** [comment] 2022-05-27 18:35
@DanielSolomon Sorry I missed that, would you mind busting that out into a separate issue? I would like to treat any new requests for how things work here as bugs in the current impl. It will also help better track the discussion.

**Comment by sodul** [comment] 2022-06-07 17:48
@codyoss What is the general status for Generics support? We are holding off on upgrading to Go 1.18 until an official mockgen release is available with full support for generics. We are also looking forward to #604 which has 2 potential PRs to address it.

Thank you!

**Comment by codyoss** [comment] 2022-08-11 18:21
https://github.com/golang/mock/releases/tag/v1.7.0-rc.1

**Comment by erkanzileli** [comment] 2022-09-26 21:20
Hi guys. It works great. Thanks for your effort.

When do you think there will be a release named `v1.7.0`?

**Comment by chenyanchen** [comment] 2022-10-10 15:35
> @herlon214 Maybe. But like I said, this does not work for non-generic types today either. If anything that should be a separate issue if people have use cases for this. The way mockgen treats aliases is already not great. Depending if you use reflect vs source mode the alias will be followed or not.

Some standard struct or interface was very useful like:
```go
type Storage[K comparable, V any] interface {
	Get(K) V
	Set(K, V)
	Del(K)
}

type node[V any] struct {
	left, right *node[V]
}
```
I think no more alias in needed.

**Comment by hirikarate** [comment] 2022-12-06 17:14
I have similar problem as @VolodymyrPobochii when trying mockgen v1.7.0-rc.1. This is my code

```go
package database

type PaginationParam[TModel any] struct {
	Limit   int
	Page    int
	Sort    string
	Columns []*TModel
}

type PaginationResult[TModel any] struct {
	TotalRows  int64
	TotalPages int
	Rows       []*TModel
}

type BaseGormRepository[TEntity any] interface {
	FetchPage(ctx Context, param PaginationParam[TEntity], conditions ...any) (PaginationResult[TEntity], error)
}

type AccountGormRepository interface {
	db.BaseRepository[model.Account]
}
```

This is the error printed on console when I generated mocks in another package (`membership`). The tool wrongfully replaced the generic type with a whole file path.

**Trimmed for brevity:**

```
2022/12/06 23:51:46 Failed to format generated source code: mock/mock_account_repository.go:102:117: missing ',' in type argument list (and 1 more errors)

// FetchPage mocks base method.
func (m *MockAccountRepository) FetchPage(arg0 Context, arg1 database.PaginationParam[mycode.github.com/domain/model.Account], arg2 ...interface{}) (database.PaginationResult[mycode.github.com/model.Account], error) {
        m.ctrl.T.Helper()
        varargs := []interface{}{arg0, arg1}
        for _, a := range arg2 {
                varargs = append(varargs, a)
        }
        ret := m.ctrl.Call(m, "FetchPage", varargs...)
        ret0, _ := ret[0].(database.PaginationResult[mycode.github.com/pkg/domain/model.Account])
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

```

**Full console error:**

```
2022/12/06 23:51:46 Failed to format generated source code: mock/mock_account_repository.go:102:117: missing ',' in type argument list (and 1 more errors)

// Code generated by MockGen. DO NOT EDIT.
// Source: mycode.github.com/pkg/domain/membership (interfaces: AccountRepository)

// Package mock is a generated GoMock package.
package mock
import (
        gomock "github.com/golang/mock/gomock"
        reflect "reflect"
        database "mycode.github.com/pkg/core/database"
        model "mycode.github.com/pkg/domain/model"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
        ctrl     *gomock.Controller
        recorder *MockAccountRepositoryMockRecorder
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
        mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
        mock := &MockAccountRepository{ctrl: ctrl}
        mock.recorder = &MockAccountRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
        return m.recorder
}

// FetchPage mocks base method.
func (m *MockAccountRepository) FetchPage(arg0 Context, arg1 database.PaginationParam[mycode.github.com/domain/model.Account], arg2 ...interface{}) (database.PaginationResult[mycode.github.com/model.Account], error) {
        m.ctrl.T.Helper()
        varargs := []interface{}{arg0, arg1}
        for _, a := range arg2 {
                varargs = append(varargs, a)
        }
        ret := m.ctrl.Call(m, "FetchPage", varargs...)
        ret0, _ := ret[0].(database.PaginationResult[mycode.github.com/pkg/domain/model.Account])
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FetchPage indicates an expected call of FetchPage.
func (mr *MockAccountRepositoryMockRecorder) FetchPage(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        varargs := append([]interface{}{arg0, arg1}, arg2...)
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPage", reflect.TypeOf((*MockAccountRepository)(nil).FetchPage), varargs...)
}

pkg/domain/membership/types.go:26: running "mockgen": exit status 1
```

**Comment by mgnsk** [comment] 2023-03-17 14:15
I got generics working by using the main branch and passing the `-source` parameter to mockgen.

**Comment by rolandjitsu** [comment] 2023-03-21 05:03
> Even when trying with the `1.7.0-rc.1` I still get the same error message: `Loading input failed: don't know how to mock method of type *ast.BinaryExpr`

Getting the same issue too. Tried the main branch as well.

The issue seems to be happening when I have a constraint declaration:
```go
type Number interface {
  int64 | float64
}
```

**Comment by LuisOsta** [comment] 2023-03-23 17:22
How can we get the latest version that has the support for generics? The last release I can see (1.6) is from 2021

**Comment by codewith-luke** [comment] 2023-04-19 18:30
> > Even when trying with the `1.7.0-rc.1` I still get the same error message: `Loading input failed: don't know how to mock method of type *ast.BinaryExpr`
> 
> Getting the same issue too. Tried the main branch as well.
> 
> The issue seems to be happening when I have a constraint declaration:
> 
> ```go
> type Number interface {
>   int64 | float64
> }
> ```

Similar to you I am seeing something along the lines of `failed parsing returns: don't know how to parse type *ast.IndexExpr`

This is when going over a just any reference to my generics such as a method in an interface:

```go
Search(input InputInventorySearch) (*internal.Pagination[internal.Product], error)
```

**Comment by tareqhs** [comment] 2023-05-07 12:11
hi @codyoss , when is 1.7.0 expected to be released?
go 1.18 was released over a year ago and large codebases started adopting generics.
