### ISSUE TITLE
Does not respect a manually set GOROOT

### ISSUE THREAD

**Issue by cjcjameson** [golang/mock#193] opened 2018-06-13 00:31 UTC
This works: `mockgen github.com/newrelic/go-agent Transaction`

I was expecting that the following would work, compiling the mock using a slightly older version of Go, but it failed, as seen below.

```
→ GOROOT=/usr/local/Cellar/go/1.10/libexec mockgen github.com/newrelic/go-agent Transaction

# internal/cpu
compile: version "go1.10" does not match go tool version "go1.10.3"
# internal/race
compile: version "go1.10" does not match go tool version "go1.10.3"
⋮
⋮
# internal/nettrace
compile: version "go1.10" does not match go tool version "go1.10.3"
# vendor/golang_org/x/crypto/curve25519
compile: version "go1.10" does not match go tool version "go1.10.3"
# runtime/cgo
compile: version "go1.10" does not match go tool version "go1.10.3"
2018/06/12 17:22:44 Loading input failed: exit status 2
```

### Context / More info

*Platform*: MacOS, Go v1.10.x; Go has been `brew install`ed
*Mocking mode "reflect"* (so different from #166) --> might also be happening in source mode, not sure.
Using as an example library `github.com/newrelic/go-agent`. Haven't tested with other libraries. It happens that it was in my project's vendor directory, but it seems like it's happening irrespective of it being a vendored library.
Originally discovered in the Goland browser; I don't usually set a GOROOT in my terminal but the IDE does specify it as part of its SDK specification, and if you open a terminal within the IDE, you get the same setting.

**Comment by codyoss** [comment] 2019-10-18 19:18
Hey @cjcjameson, is this still an issue for you in the new world of modules?

**Comment by cjcjameson** [comment] 2019-10-28 05:03
Sorry, haven't come across this recently, so a little stale. Should I try
with a more recent version of Golang, or is it the more recent version of
`mock` that I should try?

**Comment by codyoss** [comment] 2019-10-31 04:06
If you have time to try a more recent version, of mockgen, that would be great! I tried to reproduce this but was unable to. I have seen some other issues that make me think it has something to do with the fact the install is via homebrew... I will try to look into this more myself as well.

**Comment by codyoss** [comment] 2019-12-13 20:55
Closing, can't reproduce. If this become a problem again and you have a sample to reproduce this feel free to reopen.

**Closed by codyoss** 2019-12-13 20:55 UTC
Labels: modules, status: needs more info, type: feature request

**Comment by marinagre-px** [comment] 2022-02-23 14:16
happens to me on version 1.6.0
compile: version "go1.17.6" does not match go tool version "go1.17.3"

**Comment by codyoss** [comment] 2022-02-23 15:29
It sounds like you have multiple installs of Go. Make sure you are using the same Go that is set as your GOROOT.
