### ISSUE TITLE
Unexpected argument errors gives a segfault

### ISSUE THREAD

**Issue by AntonNguyen** [golang/mock#425] opened 2020-04-08 02:36 UTC
**Actual behavior** 
When a mock is setup, but the wrong arguments are passed in, the test should fail with the following message:

```
main_test.go:113: missing call(s) to *mocks.MockService.MyMockedFunction(is anything, is equal to {[0xc00015e140 0xc00015e280]   }) main_test.go:2436
```

**Expected behavior**
happen.

A null pointer exception!

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x185e5ad]

goroutine 114 [running]:
github.com/golang/mock/gomock.(*Call).dropPrereqs(...)
	/Users/anton/go/pkg/mod/github.com/golang/mock@v1.4.3/gomock/call.go:401
github.com/golang/mock/gomock.(*Controller).Call.func1(0xc0000d12f0, 0x1a91600, 0xc0000cd990, 0x1b0e095, 0x1e, 0xc00013ee00, 0x2, 0x2, 0x0, 0x0, ...)
	/Users/anton/go/pkg/mod/github.com/golang/mock@v1.4.3/gomock/controller.go:207 +0x15d
github.com/golang/mock/gomock.(*Controller).Call(0xc0000d12f0, 0x1a91600, 0xc0000cd990, 0x1b0e095, 0x1e, 0xc00013ee00, 0x2, 0x2, 0x0, 0x0, ...)
	/Users/anton/go/pkg/mod/github.com/golang/mock@v1.4.3/gomock/controller.go:217 +0xb4
```

**To Reproduce**

When I put a debugger into `controller.go`:
https://github.com/golang/mock/blob/3a35fb6e3e18b9dbfee291262260dee7372d2a92/gomock/controller.go#L198-L202

After `ctrl.T.Fatal` is called, the code _continues_ (instead of unlocking and returning). At this point, `expected` is `nil`, so when `expected.dropPrereqs()` is executed, I get the null pointer exception.

**Additional Information**

-   gomock mode: `source`
-   gomock version: `1.4.3`:
-   golang version: `1.14`

**Triage Notes for the Maintainers**

**Comment by codyoss** [comment] 2020-04-08 14:44
I think we have another issue open for something similar, but I will check later. Thanks for the report.

**Comment by AntonNguyen** [comment] 2020-04-14 21:07
I was able to solve this issue by having my reporter send a panic:

```golang
type goroutineReporter struct {
	T *testing.T
}

func (r goroutineReporter) Errorf(format string, args ...interface{}) {
	r.T.Errorf(format, args...)
}

func (r goroutineReporter) Fatalf(format string, args ...interface{}) {
	panic(fmt.Sprintf(format, args...))
}
```

Then in my mock setup, I pass in the reporter:

```golang
	reporter := goroutineReporter{
		T: t,
	}
	controller := gomock.NewController(reporter)
```

**Comment by codyoss** [comment] 2020-04-15 23:27
I think this is a duplicate of #145. Let me know if you think that is not the case.

**Comment by codyoss** [comment] 2020-04-24 21:10
Closing as duplicate, the issues are linked for context.

**Closed by codyoss** 2020-04-24 21:10 UTC
