### ISSUE TITLE
mockgen does not work with type alias

### ISSUE THREAD

**Issue by yiminc** [golang/mock#144] opened 2018-01-22 20:10 UTC
golang 1.9 introduce this type alias feature where you can define type as alias of another type.
There are many different legit use case of that type alias.
The mockgen does not seem to be able to generate mocks for type alias.

For example, If i define Foo as interface, then define Bar as alias of Foo, and I want to generate mock for Bar, it won't work.

**Comment by jmhodges** [comment] 2019-02-08 19:35
Ah, I think the problem is with source mode. It's non-obvious why that wouldn't work

**Comment by jmhodges** [comment] 2019-02-08 19:38
(Well, it is obvious after you remember how source mode works, of course! source mode can't import other packages)

**Comment by codyoss** [comment] 2019-10-12 20:44
I think this sounds like a good place for some better docs.

**Comment by codyoss** [comment] 2020-01-15 03:20
mockgen does work with alias, but I think only correctly with source mode. This feature request is being tracked in #244. I am going to close this one for now as the other has more active discussion talking place. If there is more to be said, lets say it over there.

**Closed by codyoss** 2020-01-15 03:20 UTC
Labels: help wanted, type: docs
