### ISSUE TITLE
imported package collision: "backoff" imported twice

### ISSUE THREAD

**Issue by arjunsingri** [golang/mock#401] opened 2020-02-21 04:40 UTC
**Actual behavior** A clear and concise description of what the bug is.
When I run mockgen for my pb.go files, I get the error below:

`2020/02/20 16:29:15 imported package collision: "backoff" imported twice`

**Expected behavior** A clear and concise description of what you expected to
happen.
No error is generated and the mocks are generated as well.

**To Reproduce** Steps to reproduce the behavior

1.  Install mockgen 1.4
2.  Generate mocks using the command below:

`mockgen -source=./file.pb.go -package=mock`

**Additional Information**

-   gomock mode (reflect or source): tried both
-   gomock version or git ref: 1.4.0
-   golang version: tried with go1.11 and go1.13

**Comment by codyoss** [comment] 2020-02-21 23:19
Could you please provide us a small code snippet of what a `file.pb.go`  looks like so I can try to reproduce this?

**Comment by codyoss** [comment] 2020-02-22 07:39
Closing this as a dupe of #156. Lets move all relevant discussion there.

**Closed by codyoss** 2020-02-22 07:39 UTC
Labels: status: needs more info, type: question
