### ISSUE TITLE
Support for Generics

### ISSUE THREAD

**Issue by gurleensethi** [golang/mock#635] opened 2022-04-15 22:42 UTC
*Requested feature*
Ability to create mocks when interfaces have generics used inside them.

*Why the feature is needed*
When I try to generate mocks I get this error:
```
2022/04/15 18:38:12 Loading input failed: service/my_service.go:7:11: failed parsing returns: don't know how to parse type *ast.IndexExpr
```

Would appreciate this feature being supported, for now it makes the combination go1.8 and gomock unusable.

**Comment by sodul** [comment] 2022-04-18 17:44
I think this is a duplicate of #621

**Comment by codyoss** [comment] 2022-04-24 19:22
Closing as dupe as mentioned above.

**Closed by codyoss** 2022-04-24 19:22 UTC
Labels: type: feature request
