### ISSUE TITLE
Better output when Unexpected call

### ISSUE THREAD

**Issue by lovung** [golang/mock#501] opened 2020-11-24 09:12 UTC
**Requested feature**
- Should have better output when having `Unexpected call`
- Can see the diff between `Got` and `Want` on EXPECT()

**Why the feature is needed**
Currently, I have some output like that. It's hard to see what is wrong.
```sh
|| Got: {{0 01ENSP2J4H9QRMWYJ3ZQTYEGYJ 0001-01-01 00:00:00 +0000 UTC {0001-01-01 00:00:00 +0000 UTC false} 2020-10-10 00:00:00 +0000 UTC <nil>} 0 <nil> 0 name namekana code 123 50 20 {0 63737366400 <nil>} {0 63737452800 <nil>} {0 0 <nil>} 1000 1 0  0 <nil>     11 10 0 0 0 20 10 0 0 0 21 10 0 0 0 0 0   0 0 [{0 01ENSP2J4H9QRMWYJ3ZQTYEGYJ}] [] [] []  <nil> <nil> [] []  {0  0001-01-01 00:00:00 +0000 UTC <nil> 0 0001-01-01 00:00:00 +0000 UTC 0 {0001-01-01 00:00:00 +0000 UTC false} <nil> 0 {0 0           0 0        0    false false false false false false false false false     false false  0  0001-01-01 00:00:00 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC 0}      [] [] } {0 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC 0 0 0   0 0  0  0    } <nil> {{0  }} {{0  }} {{0  }} {{0  }} {{0  }} {{0  }} {{0  }} {{0  }}}
|| Want: is equal to {{0 01ENSP2J4H9QRMWYJ3ZQTYEGYJ 0001-01-01 00:00:00 +0000 UTC {0001-01-01 00:00:00 +0000 UTC false} 2020-10-10 00:00:00 +0000 UTC <nil>} 0 <nil> 0 name namekana code 123 50 50 {0 63737366400 <nil>} {0 63737452800 <nil>} {0 0 <nil>} 1000 1 0  0 <nil>     11 10 0 0 0 20 10 0 0 0 21 10 0 0 0 0 0   0 0 [] [] [] []  <nil> <nil> [] []  {0  0001-01-01 00:00:00 +0000 UTC <nil> 0 0001-01-01 00:00:00 +0000 UTC 0 {0001-01-01 00:00:00 +0000 UTC false} <nil> 0 {0 0           0 0        0    false false false false false false false false false     false false  0  0001-01-01 00:00:00 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC 0}      [] [] } {0 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC 0 0 0   0 0  0  0    } <nil> {{0  }} {{0  }} {{0  }} {{0  }} {{0  }} {{0  }} {{0  }} {{0  }}}
```

**Proposed solution**
 - Using [cmp](https://github.com/google/go-cmp).Diff for output

**Comment by codyoss** [comment] 2020-12-10 16:48
Thanks for the report, closing as a duplicate of #265.

**Closed by codyoss** 2020-12-10 16:48 UTC
Labels: type: feature request
